### ISSUE TITLE
chaoimage.repository is not applied to chao-deployment.yaml

### ISSUE THREAD

**Issue by homingli** [gremlin/helm#19]
Command:

```
$ helm install gremlin/gremlin --dry-run --debug --namespace gremlin --set image.repository=xxx.amazonaws.com/gremlin/gremlin --set image.tag=latest --set chaoimage.repository=xxx.amazonaws.com/gremlin/chao --set chaoimage.tag=latest --set gremlin.secret.managed=true --set gremlin.secret.type=secret --set gremlin.secret.teamID=$GREMLIN_TEAM_ID --set gremlin.secret.clusterID=$GREMLIN_CLUSTER_ID --set gremlin.secret.teamSecret=$GREMLIN_TEAM_SECRET --generate-name
```

Output:

```
---
# Source: gremlin/templates/chao-deployment.yaml
apiVersion: apps/v1
kind: Deployment
(...)
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: chao
        app.kubernetes.io/name: chao
        app.kubernetes.io/version: "1"
    spec:
      serviceAccountName: chao
      containers:
        - image: gremlin/chao:latest
```

Version:

```
$ helm show chart gremlin/gremlin
apiVersion: v1
appVersion: 2.12.21
description: The Gremlin Inc client application
home: https://www.gremlin.com
maintainers:
- email: thor@gremlin.com
  name: Sean "thor" Swehla
- email: phil@gremlin.com
  name: Philip Gebhardt
name: gremlin
version: 0.1.8
```
